/*
 * Godot Asset Store API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiOverviewData {
    /// Exact API version using semantic versioning.
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    /// URL to the automatically generated API specifification in OpenAPI format.
    #[serde(rename = "openapi_spec", skip_serializing_if = "Option::is_none")]
    pub openapi_spec: Option<String>,
    /// URL to the automatically generated API documentation (Swagger UI).
    #[serde(rename = "docs_swagger", skip_serializing_if = "Option::is_none")]
    pub docs_swagger: Option<String>,
    /// URL to the automatically generated API documentation (Redoc).
    #[serde(rename = "docs_redoc", skip_serializing_if = "Option::is_none")]
    pub docs_redoc: Option<String>,
}

impl ApiOverviewData {
    pub fn new() -> ApiOverviewData {
        ApiOverviewData {
            version: None,
            openapi_spec: None,
            docs_swagger: None,
            docs_redoc: None,
        }
    }
}

