/*
 * Godot Asset Store API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetDataDetailed {
    /// Unique identifier for the Asset.
    #[serde(rename = "slug", skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
    /// Publisher of this asset
    #[serde(rename = "publisher", skip_serializing_if = "Option::is_none")]
    pub publisher: Option<Box<models::PublisherData>>,
    /// Human readable display name.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Small summary of the asset page.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Price in cents (Euro).
    #[serde(rename = "price_cent", skip_serializing_if = "Option::is_none")]
    pub price_cent: Option<i32>,
    /// Name of the license.
    #[serde(rename = "license_type", skip_serializing_if = "Option::is_none")]
    pub license_type: Option<String>,
    /// URL to the exact terms of the license.
    #[serde(rename = "license_url", skip_serializing_if = "Option::is_none")]
    pub license_url: Option<String>,
    #[serde(
        rename = "thumbnail",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub thumbnail: Option<Option<serde_json::Value>>,
    /// Sum of upvotes (+1) and downvotes (-1).
    #[serde(rename = "reviews_score", skip_serializing_if = "Option::is_none")]
    pub reviews_score: Option<i32>,
    /// Tags that are associated with this asset.
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<models::TagData>>,
    #[serde(
        rename = "store_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub store_url: Option<Option<serde_json::Value>>,
    /// Content of the asset page rendered as HTML.
    #[serde(rename = "body_html", skip_serializing_if = "Option::is_none")]
    pub body_html: Option<String>,
    /// Content of the asset page rendered as BBCode.
    #[serde(rename = "body_bbcode", skip_serializing_if = "Option::is_none")]
    pub body_bbcode: Option<String>,
    /// Call to action that can be displayed on the donation button.
    #[serde(rename = "donation_text", skip_serializing_if = "Option::is_none")]
    pub donation_text: Option<String>,
    /// URL to an external donation page for the asset.  **Note:** The target page is neither hosted by nor affiliated with the Godot Foundation.
    #[serde(rename = "donation_url", skip_serializing_if = "Option::is_none")]
    pub donation_url: Option<String>,
    /// URL leading to an external page hosting the source code.  **Note:** The target page is neither hosted by nor affiliated with the Godot Foundation.
    #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
    #[serde(
        rename = "featured_thumbnail",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub featured_thumbnail: Option<Option<serde_json::Value>>,
    #[serde(
        rename = "media",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub media: Option<Option<serde_json::Value>>,
    /// URL to an external video.  **Note:** The target page is neither hosted by nor affiliated with the Godot Foundation.
    #[serde(rename = "video_id", skip_serializing_if = "Option::is_none")]
    pub video_id: Option<String>,
    /// Date time in iso format specifying the creation date.
    #[serde(rename = "created", skip_serializing_if = "Option::is_none")]
    pub created: Option<String>,
    /// Date time in iso format specifying the last modification date.
    #[serde(rename = "last_updated", skip_serializing_if = "Option::is_none")]
    pub last_updated: Option<String>,
    /// True if the asset is currently featured.
    #[serde(rename = "featured", skip_serializing_if = "Option::is_none")]
    pub featured: Option<bool>,
    #[serde(
        rename = "video_playback_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub video_playback_url: Option<Option<serde_json::Value>>,
    #[serde(
        rename = "video_embed_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub video_embed_url: Option<Option<serde_json::Value>>,
    #[serde(
        rename = "video_thumbnail_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub video_thumbnail_url: Option<Option<serde_json::Value>>,
}

impl AssetDataDetailed {
    pub fn new() -> AssetDataDetailed {
        AssetDataDetailed {
            slug: None,
            publisher: None,
            name: None,
            description: None,
            price_cent: None,
            license_type: None,
            license_url: None,
            thumbnail: None,
            reviews_score: None,
            tags: None,
            store_url: None,
            body_html: None,
            body_bbcode: None,
            donation_text: None,
            donation_url: None,
            source: None,
            featured_thumbnail: None,
            media: None,
            video_id: None,
            created: None,
            last_updated: None,
            featured: None,
            video_playback_url: None,
            video_embed_url: None,
            video_thumbnail_url: None,
        }
    }
}
