/*
 * Godot Asset Store API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetData {
    /// Unique identifier for the Asset.
    #[serde(rename = "slug", skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
    /// Publisher of this asset
    #[serde(rename = "publisher", skip_serializing_if = "Option::is_none")]
    pub publisher: Option<Box<models::PublisherData>>,
    /// Human readable display name.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Small summary of the asset page.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Price in cents (Euro).
    #[serde(rename = "price_cent", skip_serializing_if = "Option::is_none")]
    pub price_cent: Option<i32>,
    /// Name of the license.
    #[serde(rename = "license_type", skip_serializing_if = "Option::is_none")]
    pub license_type: Option<String>,
    /// URL to the exact terms of the license.
    #[serde(rename = "license_url", skip_serializing_if = "Option::is_none")]
    pub license_url: Option<String>,
    #[serde(rename = "thumbnail", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub thumbnail: Option<Option<serde_json::Value>>,
    /// Sum of upvotes (+1) and downvotes (-1).
    #[serde(rename = "reviews_score", skip_serializing_if = "Option::is_none")]
    pub reviews_score: Option<i32>,
    /// Tags that are associated with this asset.
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<models::TagData>>,
    #[serde(rename = "store_url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub store_url: Option<Option<serde_json::Value>>,
}

impl AssetData {
    pub fn new() -> AssetData {
        AssetData {
            slug: None,
            publisher: None,
            name: None,
            description: None,
            price_cent: None,
            license_type: None,
            license_url: None,
            thumbnail: None,
            reviews_score: None,
            tags: None,
            store_url: None,
        }
    }
}

