/*
 * Godot Asset Store API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChangelogEntry {
    /// Description of the change.
    #[serde(rename = "text", skip_serializing_if = "Option::is_none")]
    pub text: Option<String>,
    /// Issue number of the public GitHub issue (-1 if none exists).
    #[serde(rename = "issue_number", skip_serializing_if = "Option::is_none")]
    pub issue_number: Option<i32>,
    /// Link to a public GitHub issue.
    #[serde(rename = "issue_link", skip_serializing_if = "Option::is_none")]
    pub issue_link: Option<String>,
}

impl ChangelogEntry {
    pub fn new() -> ChangelogEntry {
        ChangelogEntry {
            text: None,
            issue_number: None,
            issue_link: None,
        }
    }
}

