/*
 * Godot Asset Store API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaginationMetadata {
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<i32>,
    #[serde(rename = "total_pages", skip_serializing_if = "Option::is_none")]
    pub total_pages: Option<i32>,
    #[serde(rename = "first_page", skip_serializing_if = "Option::is_none")]
    pub first_page: Option<i32>,
    #[serde(rename = "last_page", skip_serializing_if = "Option::is_none")]
    pub last_page: Option<i32>,
    #[serde(rename = "page", skip_serializing_if = "Option::is_none")]
    pub page: Option<i32>,
    #[serde(rename = "previous_page", skip_serializing_if = "Option::is_none")]
    pub previous_page: Option<i32>,
    #[serde(rename = "next_page", skip_serializing_if = "Option::is_none")]
    pub next_page: Option<i32>,
}

impl PaginationMetadata {
    pub fn new() -> PaginationMetadata {
        PaginationMetadata {
            total: None,
            total_pages: None,
            first_page: None,
            last_page: None,
            page: None,
            previous_page: None,
            next_page: None,
        }
    }
}

