/*
 * Godot Asset Store API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublisherData {
    /// Unique identifier for the Publisher.
    #[serde(rename = "slug", skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
    /// Human readable display name.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "thumbnail", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub thumbnail: Option<Option<serde_json::Value>>,
    #[serde(rename = "store_url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub store_url: Option<Option<serde_json::Value>>,
}

impl PublisherData {
    pub fn new() -> PublisherData {
        PublisherData {
            slug: None,
            name: None,
            thumbnail: None,
            store_url: None,
        }
    }
}

