/*
 * Godot Asset Store API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublisherDataDetailed {
    /// Unique identifier for the Publisher.
    #[serde(rename = "slug", skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
    /// Human readable display name.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(
        rename = "thumbnail",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub thumbnail: Option<Option<serde_json::Value>>,
    #[serde(
        rename = "store_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub store_url: Option<Option<serde_json::Value>>,
    /// Description rendered as HTML
    #[serde(rename = "description_html", skip_serializing_if = "Option::is_none")]
    pub description_html: Option<String>,
    /// Description rendered as BBCode.
    #[serde(rename = "description_bbcode", skip_serializing_if = "Option::is_none")]
    pub description_bbcode: Option<String>,
    /// List of URLs provided by the publisher.  **Note:** The target page is neither hosted by nor affiliated with the Godot Foundation.
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<Vec<String>>,
}

impl PublisherDataDetailed {
    pub fn new() -> PublisherDataDetailed {
        PublisherDataDetailed {
            slug: None,
            name: None,
            thumbnail: None,
            store_url: None,
            description_html: None,
            description_bbcode: None,
            links: None,
        }
    }
}
