/*
 * Godot Asset Store API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReleaseData {
    /// ID of the asset release.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// Display name of the release.  **Note:** This is not a unique identifier, use the ID instead.
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    /// True if this is a stable release of the asset.
    #[serde(rename = "stable", skip_serializing_if = "Option::is_none")]
    pub stable: Option<bool>,
    /// Size of the release in MB.
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<f32>,
    /// Date when the release was created.
    #[serde(rename = "created", skip_serializing_if = "Option::is_none")]
    pub created: Option<String>,
    /// Minimum Godot Version.
    #[serde(rename = "min_godot_version", skip_serializing_if = "Option::is_none")]
    pub min_godot_version: Option<String>,
    /// Maximum Godot Version.
    #[serde(rename = "max_godot_version", skip_serializing_if = "Option::is_none")]
    pub max_godot_version: Option<String>,
    /// Release notes.
    #[serde(rename = "notes", skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    /// Changelog for the version rendered as HTML.
    #[serde(rename = "changes_html", skip_serializing_if = "Option::is_none")]
    pub changes_html: Option<String>,
    /// Changelog for the version rendered as BBCode.
    #[serde(rename = "changes_bbcode", skip_serializing_if = "Option::is_none")]
    pub changes_bbcode: Option<String>,
    /// URL pointing to a downloadable file.
    #[serde(rename = "download_url", skip_serializing_if = "Option::is_none")]
    pub download_url: Option<String>,
}

impl ReleaseData {
    pub fn new() -> ReleaseData {
        ReleaseData {
            id: None,
            version: None,
            stable: None,
            size: None,
            created: None,
            min_godot_version: None,
            max_godot_version: None,
            notes: None,
            changes_html: None,
            changes_bbcode: None,
            download_url: None,
        }
    }
}
