/*
 * Godot Asset Store API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{ContentType, Error, configuration};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};

/// struct for typed errors of method [`api_v1_releases_publisher_slug_asset_slug_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApiV1ReleasesPublisherSlugAssetSlugGetError {
    Status422(models::Error),
    DefaultResponse(models::Error),
    UnknownValue(serde_json::Value),
}

pub async fn api_v1_releases_publisher_slug_asset_slug_get(
    configuration: &configuration::Configuration,
    publisher_slug: &str,
    asset_slug: &str,
    stable_only: Option<bool>,
    compatibility: Option<&str>,
) -> Result<Vec<models::ReleaseData>, Error<ApiV1ReleasesPublisherSlugAssetSlugGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_publisher_slug = publisher_slug;
    let p_path_asset_slug = asset_slug;
    let p_query_stable_only = stable_only;
    let p_query_compatibility = compatibility;

    let uri_str = format!(
        "{}/api/v1/releases/{publisher_slug}/{asset_slug}/",
        configuration.base_path,
        publisher_slug = crate::apis::urlencode(p_path_publisher_slug),
        asset_slug = crate::apis::urlencode(p_path_asset_slug)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_stable_only {
        req_builder = req_builder.query(&[("stable_only", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_compatibility {
        req_builder = req_builder.query(&[("compatibility", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `Vec&lt;models::ReleaseData&gt;`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::ReleaseData&gt;`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ApiV1ReleasesPublisherSlugAssetSlugGetError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
