/*
 * Godot Asset Store API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{ContentType, Error, configuration};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};

/// struct for typed errors of method [`api_v1_search_autocomplete_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApiV1SearchAutocompleteGetError {
    Status422(models::Error),
    DefaultResponse(models::Error),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`api_v1_search_query_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApiV1SearchQueryGetError {
    Status422(models::Error),
    DefaultResponse(models::Error),
    UnknownValue(serde_json::Value),
}

pub async fn api_v1_search_autocomplete_get(
    configuration: &configuration::Configuration,
    query: &str,
    layouts: Option<Vec<String>>,
) -> Result<Vec<models::AutocompleteResult>, Error<ApiV1SearchAutocompleteGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_query = query;
    let p_query_layouts = layouts;

    let uri_str = format!("{}/api/v1/search/autocomplete/", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("query", &p_query_query.to_string())]);
    if let Some(ref param_value) = p_query_layouts {
        req_builder = match "multi" {
            "multi" => req_builder.query(
                &param_value
                    .into_iter()
                    .map(|p| ("layouts".to_owned(), p.to_string()))
                    .collect::<Vec<(std::string::String, std::string::String)>>(),
            ),
            _ => req_builder.query(&[(
                "layouts",
                &param_value
                    .into_iter()
                    .map(|p| p.to_string())
                    .collect::<Vec<String>>()
                    .join(",")
                    .to_string(),
            )]),
        };
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `Vec&lt;models::AutocompleteResult&gt;`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::AutocompleteResult&gt;`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ApiV1SearchAutocompleteGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn api_v1_search_query_get(
    configuration: &configuration::Configuration,
    query: &str,
    featured_only: Option<bool>,
    require_release: Option<bool>,
    stable_only: Option<bool>,
    compatibility: Option<&str>,
    sort: Option<&str>,
    licenses: Option<Vec<String>>,
    scroll: Option<&str>,
    page: Option<i32>,
    batch_size: Option<i32>,
) -> Result<models::SearchResults, Error<ApiV1SearchQueryGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_query = query;
    let p_query_featured_only = featured_only;
    let p_query_require_release = require_release;
    let p_query_stable_only = stable_only;
    let p_query_compatibility = compatibility;
    let p_query_sort = sort;
    let p_query_licenses = licenses;
    let p_query_scroll = scroll;
    let p_query_page = page;
    let p_query_batch_size = batch_size;

    let uri_str = format!("{}/api/v1/search/query/", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_featured_only {
        req_builder = req_builder.query(&[("featured_only", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_require_release {
        req_builder = req_builder.query(&[("require_release", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_stable_only {
        req_builder = req_builder.query(&[("stable_only", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_compatibility {
        req_builder = req_builder.query(&[("compatibility", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("query", &p_query_query.to_string())]);
    if let Some(ref param_value) = p_query_sort {
        req_builder = req_builder.query(&[("sort", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_licenses {
        req_builder = match "multi" {
            "multi" => req_builder.query(
                &param_value
                    .into_iter()
                    .map(|p| ("licenses".to_owned(), p.to_string()))
                    .collect::<Vec<(std::string::String, std::string::String)>>(),
            ),
            _ => req_builder.query(&[(
                "licenses",
                &param_value
                    .into_iter()
                    .map(|p| p.to_string())
                    .collect::<Vec<String>>()
                    .join(",")
                    .to_string(),
            )]),
        };
    }
    if let Some(ref param_value) = p_query_scroll {
        req_builder = req_builder.query(&[("scroll", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_page {
        req_builder = req_builder.query(&[("page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_batch_size {
        req_builder = req_builder.query(&[("batch_size", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::SearchResults`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::SearchResults`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ApiV1SearchQueryGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
