GET https://godotengine.org/asset-library/api/asset/4107

# Example response
{
  "asset_id": "1709",
  "type": "addon",
  "title": "GUT - Godot Unit Testing (Godot 4)",
  "author": "bitwes",
  "author_id": "115",
  "version": "11",
  "version_string": "9.5.0",
  "category": "Tools",
  "category_id": "5",
  "godot_version": "4.5",
  "rating": "0",
  "cost": "MIT",
  "description": "GUT for Godot 4.5\r\n\r\nThis release requires Godot 4.5.  You can find a full list of earlier versions and links in the README:  https:\/\/github.com\/bitwes\/Gut\/blob\/main\/README.md\r\n\r\nGUT stands for Godot Unit Testing and...as you may guess, it is a tool for creating and running tests.\r\n\r\nFeatures\r\n* Run tests easily through the Godot Editor, Command Line, or VSCode.\r\n* A plethora of asserts and utility methods to help make your tests simple and concise.\r\n* Support for Inner Test Classes to give your tests some extra context and maintainability.\r\n* Doubling: Full and Partial doubles, Stubbing, Spies.\r\n* Parameterized Tests\r\n* Export results in standard JUnit XML format.\r\n\r\nMore info can be found in the wiki: https:\/\/gut.readthedocs.io\/en\/latest\/",
  "support_level": "community",
  "download_provider": "GitHub",
  "download_commit": "8255c6305761754748f9fd641da5fd8f51c1708a",
  "browse_url": "https:\/\/github.com\/bitwes\/Gut",
  "issues_url": "https:\/\/github.com\/bitwes\/Gut\/issues",
  "icon_url": "https:\/\/raw.githubusercontent.com\/bitwes\/Gut\/main\/images\/asset_lib_icon.png",
  "searchable": "1",
  "modify_date": "2025-09-17 19:10:18",
  "download_url": "https:\/\/github.com\/bitwes\/Gut\/archive\/8255c6305761754748f9fd641da5fd8f51c1708a.zip",
  "previews": [],
  "download_hash": ""
}