GET https://godotengine.org/asset-library/api/asset?godot_version=4.5&filter="Godot Unit Testing"

# Optional query parameters:
# ?type=(any|addon|project)
# &category=(category id)
# &support=(official|featured|community|testing)
# &filter=(search text)
# &user=(submitter username)
# &cost=(license)
# &godot_version=(major).(minor).(patch)
# &max_results=(number 1…500)
# &page=(number, pages to skip) OR &offset=(number, rows to skip)
# &sort=(rating|cost|name|updated)
# &reverse

# Example response
{
  "result": [
    {
      "asset_id": "1709",
      "title": "GUT - Godot Unit Testing (Godot 4)",
      "author": "bitwes",
      "author_id": "115",
      "category": "Tools",
      "category_id": "5",
      "godot_version": "4.5",
      "rating": "0",
      "cost": "MIT",
      "support_level": "community",
      "icon_url": "https:\/\/raw.githubusercontent.com\/bitwes\/Gut\/main\/images\/asset_lib_icon.png",
      "version": "11",
      "version_string": "9.5.0",
      "modify_date": "2025-09-17 19:10:18"
    }
  ],
  "page": 0,
  "pages": 1,
  "page_length": 40,
  "total_items": 1
}
